# Generated by Django 5.0.2 on 2024-02-17 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='emil',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='passwoerd',
            new_name='password',
        ),
    ]
